services:
  rabbitmq:
    labels:
      app: rabbitmq
    image: bitnami/rabbitmq
    public: true
    scale: 2
    environment:
      - RABBITMQ_USERNAME=root
      - RABBITMQ_PASSWORD=${PASSWORD}
      - RABBITMQ_ERL_COOKIE=4aZ2gz3Sz3kdwHW5
      - RABBITMQ_MANAGEMENT_PORT_NUMBER=8080
    ports:
      - 8080
      - 5672
    volumes:
      - mq:/bitnami/rabbitmq

volumes:
  mq:
    driver_opts:
      size: 1Gi