services:
  rabbitmq:
    image: bitnami/rabbitmq
    public: true
    scale: 1
    environment:
      - RABBITMQ_USERNAME=root
      - RABBITMQ_PASSWORD=${PASSWORD}
      - RABBITMQ_ERL_COOKIE=4aZ2gz3Sz3kdwHW5
    ports:
      - 8080:15672
    volumes:
      - mq:/bitnami/rabbitmq

volumes:
  mq:
    driver_opts:
      size: 1Gi