services:
  code:
    image: ghcr.io/a224327780/code-server
    scale: 1
    ports:
      - 8080:7071
    environment:
      - PASSWORD=admin001
    volumes:
      - code:/data

volumes:
  code:
    driver_opts:
      size: 3Gi